In [3]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import sklearn
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('MergedWithBrightness6.8_mr.csv')

/Users/Singsing/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df.dropna()

,SecondsViewed_x,star,dirctor.ranking,producer.ranking,actor1SB,actor1SBrankge,actor1.ranking,actor1 BS,actor2SB,actor2SBrange,...,actor_avg,actpr_avg_BS,1,2,3,4,5,6,7,Count of Week.of.Programme.Viewing
0,898,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
1,1711,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,2
2,3798,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
3,1289,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
4,3427,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
5,1578,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
6,1072,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
7,776,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
8,343,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
9,1441,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
10,1235,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
11,4031,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
12,4163,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,2
13,1073,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
14,1322,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
15,136,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
16,2010,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,2
17,1802,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
18,969,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
19,4256,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,3
20,1033,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
21,338,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
22,1517,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
23,175,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
24,687,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
25,7391,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,2
26,1401,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
27,2729,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
28,1900,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
29,115,108707,598952,3369444,126.287529,0,5497,7,184.290966,1,...,31953.000000,44,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68470,5065,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68471,1117,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68472,9511,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,9
68473,1324,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,2
68474,5677,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,5
68475,8927,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,7
68476,10053,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,5
68477,1534,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,2
68478,8405,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,5
68479,491,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68480,5283,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68481,1218,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68482,1428,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68483,4694,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,2
68484,892,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68485,2345,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,3
68486,1135,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68487,11603,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,9
68488,1108,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68489,309,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68490,7769,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,3
68491,2118,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,2
68492,8450,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,7
68493,11649,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,8
68494,4708,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,3
68495,11907,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,6
68496,847,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68497,2116,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,1
68498,11306,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,7
68499,12584,868,53253,1079,163.787927,0,755,-7,205.554460,1,...,2728.666667,3,0,0,0,1,0,0,0,3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68500 entries, 0 to 68499
Data columns (total 26 columns):
SecondsViewed_x                       68500 non-null int64
star                                  68500 non-null object
dirctor.ranking                       68500 non-null int64
producer.ranking                      68500 non-null int64
actor1SB                              68500 non-null float64
actor1SBrankge                        68500 non-null int64
actor1.ranking                        68500 non-null int64
actor1 BS                             68500 non-null int64
actor2SB                              68500 non-null float64
actor2SBrange                         68500 non-null int64
actor2.ranking                        68500 non-null int64
actor2 BS                             68500 non-null int64
actor3SB                              68500 non-null float64
actor3SBrange                         68500 non-null int64
actor3.ranking                        68500 non-null int64
actor3 BS                             68500 non-null int64
actor_avg                             68500 non-null float64
actpr_avg_BS                          68500 non-null int64
1                                     68500 non-null int64
2                                     68500 non-null int64
3                                     68500 non-null int64
4                                     68500 non-null int64
5                                     68500 non-null int64
6                                     68500 non-null int64
7                                     68500 non-null int64
Count of Week.of.Programme.Viewing    68500 non-null int64
dtypes: float64(4), int64(21), object(1)
memory usage: 14.1+ MB

In [7]:
lreg = LinearRegression()

In [8]:
X_multi = df.drop('SecondsViewed_x',1)
X_multi = df.drop('star',1)
Y_target = df.SecondsViewed_x

In [9]:
lreg.fit(X_multi,Y_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [10]:
print ' The estimated intercept coefficient is %.2f ' %lreg.intercept_

 The estimated intercept coefficient is -0.00

In [11]:
print ' The number of coefficients used was %d ' % len(lreg.coef_)

 The number of coefficients used was 25

In [12]:
coeff_df = DataFrame(df.columns)
coeff_df.columns = ['Features']
coeff_df["Coefficient Estimate"] = pd.Series(lreg.coef_)
coeff_df

                              Features  Coefficient Estimate
0                      SecondsViewed_x          1.000000e+00
1                                 star          1.562529e-16
2                      dirctor.ranking         -5.314562e-17
3                     producer.ranking         -2.806043e-15
4                             actor1SB          6.413176e-14
5                       actor1SBrankge         -7.596726e-09
6                       actor1.ranking          6.599123e-14
7                            actor1 BS          2.780471e-14
8                             actor2SB          7.591664e-14
9                        actor2SBrange         -7.596726e-09
10                      actor2.ranking         -3.558134e-15
11                           actor2 BS         -1.612607e-15
12                            actor3SB          7.994929e-14
13                       actor3SBrange         -7.596727e-09
14                      actor3.ranking          1.201620e-15
15                           actor3 BS          2.279018e-08
16                           actor_avg          1.524363e-15
17                        actpr_avg_BS         -7.202737e-14
18                                   1          3.099357e-14
19                                   2          9.443682e-15
20                                   3          3.677413e-14
21                                   4         -5.084332e-14
22                                   5         -2.438279e-15
23                                   6          4.809798e-14
24                                   7          6.456195e-15
25  Count of Week.of.Programme.Viewing                   NaN

In [13]:
coeff_df.sort('Coefficient Estimate')

/Users/Singsing/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

                              Features  Coefficient Estimate
13                       actor3SBrange         -7.596727e-09
9                        actor2SBrange         -7.596726e-09
5                       actor1SBrankge         -7.596726e-09
17                        actpr_avg_BS         -7.202737e-14
21                                   4         -5.084332e-14
10                      actor2.ranking         -3.558134e-15
3                     producer.ranking         -2.806043e-15
22                                   5         -2.438279e-15
11                           actor2 BS         -1.612607e-15
2                      dirctor.ranking         -5.314562e-17
1                                 star          1.562529e-16
14                      actor3.ranking          1.201620e-15
16                           actor_avg          1.524363e-15
24                                   7          6.456195e-15
19                                   2          9.443682e-15
7                            actor1 BS          2.780471e-14
18                                   1          3.099357e-14
20                                   3          3.677413e-14
23                                   6          4.809798e-14
4                             actor1SB          6.413176e-14
6                       actor1.ranking          6.599123e-14
8                             actor2SB          7.591664e-14
12                            actor3SB          7.994929e-14
15                           actor3 BS          2.279018e-08
0                      SecondsViewed_x          1.000000e+00
25  Count of Week.of.Programme.Viewing                   NaN

In [14]:
coeff_df.to_excel('coeff_df.xlsx')